spring:
  datasource:
    url: jdbc:postgresql://db:5432/starke-db
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

download-voice-api:
  url: ${VOICE_DOWNLOADER_URL}

notifications:
  activity: ${NOTIFICATIONS_ACTIVITY:259200000}

words:
  wordsAtTheMoment: ${WORDS_AT_THE_MOMENT:12}
verbs:
  verbsAtTheMoment: ${VERBS_AT_THE_MOMENT:12}
