apiVersion: apps/v1
kind: Deployment
metadata:
  name: starke-verben-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starke-verben-bot
  template:
    metadata:
      labels:
        app: starke-verben-bot
    spec:
      containers:
        - name: starke-verben-bot
          image: kegisa/starkevebenbot:amd64
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: starke-verben-bot-local-configmap
            - secretRef:
                name: starke-verben-bot-secret