apiVersion: apps/v1
kind: Deployment
metadata:
  name: starke-verben-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starke-verben-bot
  template:
    metadata:
      labels:
        app: starke-verben-bot
    spec:
      containers:
        - name: spring-boot-app
          image: kegisa/starkevebenbot:amd64
