apiVersion: v1
kind: Service
metadata:
  name: voice-downloader-service
spec:
  selector:
    app: voice-downloader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP